### ISSUE TITLE
customize height of cursor position

### ISSUE THREAD

**Issue by AtomicNess123** [andre-r/centered-cursor-mode.el#20]
Is it possible to customize the "center" to make it maybe two thirds the page, and not half? Thanks!

**Comment by andre-r** [comment]
It is possible.

1. There is already a way to customize the position. In the released version you can choose from center, golden ratio and lines from top. Golden ratio is roughly two thirds. Do `M-x` `customize-variable` `RET` `ccm-vpos-init` `RET` and customize.
2. `(setq ccm-vpos-init '(round (* 2 (ccm-visible-text-lines)) 3))` in your init file to set to two thirds.
3. Or maybe try out the dev branch of the lib. I did some improvements. For example more possible position settings. But you might encounter (more) bugs: https://github.com/andre-r/centered-cursor-mode.el/blob/dev/centered-cursor-mode.el
4. Also you can temporarily move the position with `C-M--` and `C-M-+`.
