### ISSUE TITLE
Void-variable mouse-wheel-up-alternate-event

### ISSUE THREAD

**Issue by ttybitnik** [andre-r/centered-cursor-mode.el#26]
Hey there,

Just wanted to give a heads up - it looks like #25 broke backward compatibility. I was reinstalling my packages today via MELPA in Emacs 28.2, and the package stopped working.

I tried searching for an alternative version in MELPA-stable, but it seems like we only have the MELPA one, right?

(No big deal for me, though. I can keep a local version without these last changes until my distro updates Emacs to 29.1. Just wanted to let you guys know in case someone else runs into the same issue.)

**Comment by andre-r** [comment]
@sir4ur0n Can you please make a PR to make your change backward compatible?

**Comment by sir4ur0n** [comment]
I am not very good with Elisp, so I don't know how this should be addressed :sweat_smile: 
My fix in #25 was pure cargo-culting already

**Comment by ttybitnik** [comment]
I can share a **temporary** hotfix based on what did in my local copy. It ain't optimal though, I just encapsulated the changed function and variable behind a version check, and kept the original ones in the else.

Just a moment.

**Comment by ttybitnik** [comment]
Again, this it not optimal, but you can use it meanwhile if you wish, @andre-r. 

It would be nice to test in 29.1 if it will, de facto, be merged. I cannot do that atm.

**Comment by andre-r** [comment]
@ttybitnik Please test the latest version.

**Comment by ttybitnik** [comment]
Working like a charm, @andre-r. Thank you both for caring for this package :+1:
