### ISSUE TITLE
Centering does not take line-height into account

### ISSUE THREAD

**Issue by hkjels** [andre-r/centered-cursor-mode.el#3]
I prefer having quite a gap between lines and this seems to move the center of drastically.
Looking near the bottom of this screenshot, you can see where `point` ends up

![skjermbilde 2018-01-12 kl 10 37 03](https://user-images.githubusercontent.com/339547/34868626-b08c3302-f784-11e7-8da9-ce9803b2599a.png)

**Comment by andre-r** [comment]
Hello, I attempted a fix and it seems to work. Unfortunately I don't have much time right now to work on more fixes and features from the todo list.

**Comment by hkjels** [comment]
Hey,
I just tested `0.5.7`; unfortunately it doesn't seem like the fix did what it was suppose to. It might be my assumption of the bug that's incorrect though. I'll fork and see if I can grok your code. Would you accept a pull-request?

**Comment by hkjels** [comment]
After some debugging and resetting of `ccm-vpos-init` it works great!
I really like the package btw 👍
