### ISSUE TITLE
Selecting text with mouse is inaccurate

### ISSUE THREAD

**Issue by chaudron** [andre-r/centered-cursor-mode.el#4]
I'm using OSX with https://emacsformacosx.com and Fefora28 with xemacs with the centered-cursor-mode enabled and trying to select some text I noticed that the selection does not line up with my current cursor location and it also seems to jump/up down the buffer.

Is this a known side effect, or do I need to tweak anything further?

**Comment by andre-r** [comment]
If you referring to selecting with the mouse per dragging it is a known issue and on the to-do list. Re-centering has to be prevented when dragging the mouse. Otherwise I have not experienced what you describe.

**Comment by andre-r** [comment]
Please test with the latest release.

**Comment by chaudron** [comment]
Fixed in latest version
