### ISSUE TITLE
Play nice with recenter-top-bottom

### ISSUE THREAD

**Issue by sandinmyjoints** [andre-r/centered-cursor-mode.el#9]
This is a cool package!

I'd love for `recenter-top-bottom` to work when this mode is enabled. Currently, if I run `end-of-buffer` to jump to the end of a buffer that's longer than one viewable page, the last line of the buffer is at the bottom of the window, with point on the last character of it. 

I have `recenter-positions` defined as `(0.33 top bottom)`, so when I run `recenter-top-bottom`, I'd expect the line that point is on to be placed 33% below the top of the window -- this is what happens if centered-cursor-mode is not activated. However, when it is activated, point and the line it is on stay pinned to the bottom of the window.

**Comment by sandinmyjoints** [comment]
Nm, setting ccm-recenter-at-end-of-file t fixes this!

**Comment by DivineDominion** [comment]
Just got here to report that this is broken, then found this fix. 👍
